### ISSUE TITLE
Add documentation to aliases

### ISSUE THREAD

**Issue by gep13** [phillipsj/Cake.XdtTransform#1]
If you go ahead and add some documentation to your aliases, include examples of how things work, you can then make a PR to this repo:

https://github.com/cake-build/website

to get your Addin added to the official documentation on CakeBuild.net.

I recently did this for my Addin:

https://github.com/gep13/Cake.Gitter

and you can see my PR here:

https://github.com/cake-build/website/pull/12

and here is an example of the documentation that I added to my addin:

https://github.com/gep13/Cake.Gitter/commit/8ad43402b0290200d44ee3ba599148cfcfb95385

This is a great addin to be added to the collection :+1:

**Comment by phillipsj** [comment]
Sorry it took so long, but I just submitted the pull request and updated the documentation.

**Comment by gep13** [comment]
This was implemented here: https://github.com/cake-build/website/pull/104
