### ISSUE TITLE
upgrade cake.xdttransform to cake.core 0.26.0

### ISSUE THREAD

**Issue by yuri1313** [phillipsj/Cake.XdtTransform#13]
The current nuget available for Cake.XdtTransform is breaking after yesterday's Cake.Core upgrade to 0.26.0.
Getting the following error:

Error: The assembly 'Cake.XdtTransform, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly need to reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)

**Comment by kakrofoon** [comment]
Submitted merge request #14 to address issue

**Comment by gep13** [comment]
@yuri1313 @kakrofoon as per the recommendation in the error message, there is a workaround which you can follow while waiting for this.

On top of this, we recommend that you ALWAYS pin to a specific version of Cake, so that you don't hit this type of issue.

You can find more information about this recommendation here:

https://cakebuild.net/docs/tutorials/pinning-cake-version

**Comment by yuri1313** [comment]
Hi @gep13. We were actually using the skip arg workaround, but that's a bit risky imho. The packages.config one seems to work on our Azure deployment infra, so we're going to go with that for now.

Thanks for the quick reply :)

**Comment by phillipsj** [comment]
I will try to get this fixed this week.  Thanks @gep13 for jumping in and
responding.

**Comment by kakrofoon** [comment]
Not sure why the update is failing in my patch; it is passing all tests and working fine locally.

**Comment by phillipsj** [comment]
@kakrofoon it is the code coverage step that is erroring.  Everything looks good. I am going to work on the release process.
