### ISSUE TITLE
Version 0.15.0 is breaking dependencies

### ISSUE THREAD

**Issue by Ninglin** [phillipsj/Cake.XdtTransform#24]
So I updated to the latest version and my script stopped working. it appears that it cannot find netstandard 2.0. 
Here is the error: 
`Could not load Cake.XdtTransform (missing netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)`

**Comment by phillipsj** [comment]
Hi,

What version of Cake and .NET are you using? 

If you are using a .NET older than 4.6.2 or .NET Core 2.x you will need to either upgrade your .NET version or pin the Cake.XdtTransform in you Cake file.  You can read about pinnning here.  https://cakebuild.net/docs/tutorials/pinning-cake-version

I apologize for the inconvenience this may have caused.

**Comment by Ninglin** [comment]
I'm using Cake 0.24  and .Net 4.6.1. yeah i figured that and pinned the version to 0.14.1 until I upgrade it to .Net 4.6.2. Thanks for the herlp 😄

**Comment by phillipsj** [comment]
Your welcome.
