### ISSUE TITLE
v0.17.0 uses Cake core version 0.32.1, not 0.33.0 as announced

### ISSUE THREAD

**Issue by daghb** [phillipsj/Cake.XdtTransform#35]
There seems to be a discrepancy between what is announced (using Cake core 0.33.0) and what is actually referenced in the source. 

packages.config on the master branch says
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
    <package id="Cake" version="0.32.1" />
</packages>
```

**Comment by phillipsj** [comment]
I will debug this today and see what happened. I apologize for the
inconvenience.

**Comment by phillipsj** [comment]
@daghb I am not seeing the packages.config on master. The project file has 0.33.0 in the packages section. https://github.com/cake-contrib/Cake.XdtTransform/blob/master/src/Cake.XdtTransform/Cake.XdtTransform.csproj

**Comment by daghb** [comment]
Sorry for the inconvenience. My mistake, I looked into the ./tools folder, which is for building this project.
