### ISSUE TITLE
DotNet.Xdt Dll Missing

### ISSUE THREAD

**Issue by Vhostymr** [phillipsj/Cake.XdtTransform#42]
The newest version is missing the DotNet.Xdt dll that previous versions downloaded as a dependency and a fresh build.ps1 execution is failing.

Edit: This is for version 0.18.1

**Comment by phillipsj** [comment]
@bhurler1  you will need to add the loaddepedencies=true to the end of the addin directive so the nuget depedencies are fetched.

#addin nuget:?package=Cake.XdtTransform&version=0.18.0&loaddependencies=true

**Comment by Vhostymr** [comment]
No problem, disregard the PR then. Thanks!
