### ISSUE TITLE
Version 0.10.0 seems to have wrong assembly information

### ISSUE THREAD

**Issue by nengberg** [phillipsj/Cake.XdtTransform#5]
Hi,

I updated my plugin which uses your plugin to the latest version 0.10.0. And it seems that the file and product version does not reflect the actual version:

![image](https://cloud.githubusercontent.com/assets/2542686/24206113/a1119ee4-0f1d-11e7-81c5-049d53c984cd.png)

**Comment by phillipsj** [comment]
Thanks, I will get that corrected.
