### ISSUE TITLE
Fix FluentAssertions usages in current tests

### ISSUE THREAD

**Issue by kcamp** [phillipsj/Cake.XdtTransform#62]
There are a number of usages of `.Equals(..)` in the fluent method chains in various tests that are incorrect - they trigger no assertion and are flagged as "return value .. never used".

Issues identified exist in 
`XdtTransformationTests`, `XdtTransformationLogTests`, `XdtTransformationLogEntryTests`

These should more correctly invoke the `.Be(...)` (or equivalent) method that are extending off their respective assertion type, resulting in the correct `Assert`.

**Comment by kcamp** [comment]
Will have a PR for this shortly

**Comment by augustoproiete** [comment]
Resolved by #63
